FROM node:lts as build
WORKDIR /bundle

COPY package.json package-lock.json /bundle/
COPY . /bundle
RUN npm i
RUN npm run build && find build
EXPOSE 3000
CMD ["npm", "run", "start-swarm"]

FROM nginx:stable-alpine


RUN apk add --no-cache bash

COPY --from=build /bundle/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /bundle/build/ /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]